# This is a basic workflow to help you get started with Actions

name: delete-network-clusters

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  TERRAFORM:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      # clone terraform code 
      - uses: actions/checkout@v3
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/299409475323/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'tf-gke-dr-svc-account@k8s-exp-367504.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          gcloud version
          gcloud components install beta
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform
          cd dr-network-and-cluster
          terraform init 
          terraform destroy -auto-approve
